import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'
import './globals.css'
import Navbar from '@/component/navbar'
import Provider from './provider'

const fira_code = Fira_Code({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={fira_code.className}>
				<Provider>
					<Navbar />
					{children}
					<p>Footer</p>
				</Provider>
			</body>
		</html>
	)
}
